
class Config {

  /// Generated by Flangapp PRO 04-07-2024 09:55
  /// App UID: 84133e33-4fe3-a4c1-d984-11dbdde40c75
  /// Version: 1.0.0
  /// API server: http://appapi.1marus.ru/install/

  /// *** Main settings *** ///
  static String apiUrl = "http://appapi.1marus.ru/install/";
  static String appUid = "84133e33-4fe3-a4c1-d984-11dbdde40c75";
  static String oneSignalPushId = "dc31e591-0dad-407f-a92b-c9c3b49dc94e";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#F44336";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = false;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = false;

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "No internet connection";
  static String offlineImage = "dino.png";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "App not available";
  static String subscribeErrorMessage = "This app may have been removed or your administrator may need to renew your subscription";
}